# make_song

def make_song(verses = 99, beverage = "soda"):
    for num in range(verses, -1, -1):
        if num > 1:
            yield f"{num} bottles of {'soda'} on the wall"
        elif num == 1:
            yield f"Only {num} bottle on {'soda'} on the wall"
        else:
            yield f"No more bottles of {'soda'}!"


bottle = make_song()
print(bottle)

print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))
print(next(bottle))

        
    